export const TYPE_EXAMPLE = 'TYPE_EXAMPLE';
export const BUSCAR_COCKTAILS = 'BUSCAR_COCKTAILS';
export const COCKTAILS_OBTENIDOS = 'COCKTAILS_OBTENIDOS';
export const COCKTAILS_ERROR = 'COCKTAILS_ERROR';
export const INFO_ABIERTA = 'INFO_ABIERTA';
export const INFO_CERRADA = 'INFO_CERRADA';
