export const COCKTAILS_OBTAINED = 'COCKTAILS_OBTAINED';
export const COCKTAILS_ERROR = 'COCKTAILS_ERROR';
export const SET_ACTIVE_COCKTAIL = 'SET_ACTIVE_COCKTAIL';
export const SET_FILTER = 'SET_FILTER';
export const RETRY = 'RETRY';
